[package]
name = "cloud-backend"
version = "3.0.0"
edition = "2021"
[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rumqttc = "0.22.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "macros"] }
dotenvy = "0.15"
uuid = { version = "1.2", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
[dev-dependencies]
criterion = "0.5"
[[bench]]
name = "telemetry_benchmark"
harness = false
