name: Kasi Power CI & CD

on:
  push:
    branches: [ "moo" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  list-members:
    name: List workspace crates
    runs-on: ubuntu-latest
    outputs:
      members: ${{ steps.list.outputs.members }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get workspace members
        id: list
        run: |
          MEMBERS=$(cargo metadata --no-deps --format-version 1 | jq -r '.workspace_members | map(sub(" .*"; ""))' | jq -c .)
          echo "members=$MEMBERS" >> $GITHUB_OUTPUT

  build-and-test:
    name: Build & Test ${{ matrix.member }}
    needs: list-members
    runs-on: ubuntu-latest
    strategy:
      matrix:
        member: ${{ fromJson(needs.list-members.outputs.members) }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build crate
        run: cargo build -p ${{ matrix.member }} --verbose

      - name: Run benchmarks
        if: matrix.member == 'cloud-backend'
        run: cargo bench -p cloud-backend --verbose

  build-and-push:
    name: Build & Push Docker Images
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app: [firmware, cloud-backend]
    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/kasi-power-${{ matrix.app }}

      - name: Install nightly Rust toolchain
        run: |
          rustup toolchain install nightly --profile minimal --component rustfmt --component clippy
          rustup default nightly

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.app == 'cloud-backend' && 'Dockerfile.backend' || 'Dockerfile.firmware' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
